spring:
  datasource:
    url: jdbc:mysql://localhost/test-qa?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    ROOT: WARN